#!/bin/sh
echo "Note: Events are available from sprint2_drop3"
read -p "Enter Team(eg team_1):" team;
echo $team;
if [ -z "$team" ]; then
        echo "The sprint was left empty";
        exit;
fi

for i in `ls -1 wp_eventscalendar*.sql`; do
	/opt/lampp/bin/mysql -u root -pPlanit10 $team < $i
done
